import type { DeliveryMode } from "@aerial/shared";

/**
 * Generates the per-channel Liquidsoap script (ADR D2/D6/D8).
 *
 * Target runtime: Liquidsoap 2.2.x. The encoder, `output.file.hls`, and
 * `http.post` signatures below are written for 2.2.x — validate against the
 * exact version baked into the control-plane image before relying on it.
 *
 * Per `deliveryMode`, a channel emits one or both outputs from one pipeline:
 *   - HLS rendition set (AAC) written to `hlsDir`  → served by Caddy / CDN
 *   - one Icecast mount (MP3) pushed to the Icecast container → origin-direct
 */
export interface LiquidsoapParams {
  slug: string;
  name: string;
  mount: string; // "/<slug>"
  harborPort: number;
  deliveryMode: DeliveryMode; // which outputs to emit
  hlsBitrates: number[]; // kbps, e.g. [64, 128]
  icecastBitrate: number; // kbps MP3
  hlsDir: string; // absolute output dir for this channel's HLS
  mediaDir: string; // fallback media dir (empty => silence via mksafe)
  icecastHost: string;
  icecastPort: number;
  icecastSourcePassword: string;
  internalApiUrl: string;
  internalToken: string;
}

export function buildLiquidsoapScript(p: LiquidsoapParams): string {
  const hlsStreams = p.hlsBitrates
    .map((b) => `    ("aac_${b}", %ffmpeg(format="mpegts", %audio(codec="aac", b="${b}k")))`)
    .join(",\n");

  // Escape double quotes in interpolated strings that could contain them.
  const name = p.name.replace(/"/g, '\\"');

  const emitHls = p.deliveryMode === "hls" || p.deliveryMode === "both";
  const emitIcecast = p.deliveryMode === "icecast" || p.deliveryMode === "both";

  const hlsOutput = emitHls
    ? `
# ── Output: HLS rendition set (CDN-cacheable) ─────────────────────────────────
output.file.hls(
  playlist="live.m3u8",
  segment_duration=4.0,
  segments=6,
  segments_overhead=4,
  temp_dir="${p.hlsDir}",
  "${p.hlsDir}",
  [
${hlsStreams}
  ],
  radio
)
`
    : "";

  const icecastOutput = emitIcecast
    ? `
# ── Output: low-latency Icecast mount (origin-direct, never CDN-fronted) ──────
output.icecast(
  %mp3(bitrate=${p.icecastBitrate}),
  host="${p.icecastHost}",
  port=${p.icecastPort},
  password="${p.icecastSourcePassword}",
  mount="${p.mount}",
  name="${name}",
  radio
)
`
    : "";

  return `# ─────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED by Aerial for channel "${p.slug}". Do not edit by hand.
# Target: Liquidsoap 2.2.x
# ─────────────────────────────────────────────────────────────────────────────
log.level := 3
# Safety net if the container is overridden to run as root (it defaults to the
# non-root 'liquidsoap' user, where this is a no-op). Liquidsoap refuses root otherwise.
settings.init.allow_root := true
settings.harbor.bind_addrs := ["0.0.0.0"]

internal_url = "${p.internalApiUrl}"
internal_token = "${p.internalToken}"

# Post a small JSON body to a control-plane internal hook (fire-and-forget).
def notify(path, payload) =
  ignore(http.post(
    "#{internal_url}#{path}",
    headers=[("Content-Type", "application/json"), ("x-internal-token", internal_token)],
    data=json.stringify(payload)
  ))
end

# Harbor source auth → delegates to the control plane (bcrypt compare, D10).
# Liquidsoap 2.2 passes a record {user, password, address}.
def auth(req) =
  resp = http.post(
    "#{internal_url}/internal/auth",
    headers=[("Content-Type", "application/json"), ("x-internal-token", internal_token)],
    data=json.stringify({mount = "${p.mount}", user = req.user, password = req.password})
  )
  resp.status_code == 200
end

# Live streamer input. on_connect/on_disconnect report "live" status to the control plane.
live = input.harbor(
  "${p.mount}",
  port=${p.harborPort},
  auth=auth,
  buffer=5.0,
  max=15.0,
  on_connect=fun(_) -> notify("/internal/status", {slug = "${p.slug}", live = true}),
  on_disconnect=fun() -> notify("/internal/status", {slug = "${p.slug}", live = false})
)

# Fallback loop. mksafe guarantees the mount never drops (silence if empty).
loop = mksafe(playlist("${p.mediaDir}", mode="randomize", reload_mode="watch"))

# Instant cutover to live the moment a streamer connects (track_sensitive=false).
radio = fallback(track_sensitive=false, [live, loop])

# Loudness: placeholder normalization. TODO: replace with true EBU R128 (D12).
radio = normalize(radio)

# Now-playing side-channel (D8): push metadata to the control plane.
radio.on_metadata(fun(m) ->
  notify("/internal/metadata", {
    slug = "${p.slug}",
    title = m["title"],
    artist = m["artist"]
  })
)
${hlsOutput}${icecastOutput}`;
}
