import type { DeliveryMode } from "@aerial/shared";

/**
 * Generates the per-channel Liquidsoap script (ADR D2/D6/D8).
 *
 * Target runtime: Liquidsoap 2.2.x. The encoder, `output.file.hls`, and
 * `http.post` signatures below are written for 2.2.x — validate against the
 * exact version baked into the control-plane image before relying on it.
 *
 * Per `deliveryMode`, a channel emits one or both outputs from one pipeline:
 *   - HLS rendition set (AAC) written to `hlsDir`  → served by Caddy / CDN
 *   - one Icecast mount (MP3) pushed to the Icecast container → origin-direct
 */
export interface LiquidsoapParams {
  slug: string;
  name: string;
  mount: string; // "/<slug>"
  harborPort: number;
  deliveryMode: DeliveryMode; // which outputs to emit
  hlsBitrates: number[]; // kbps, e.g. [64, 128]
  icecastBitrate: number; // kbps MP3
  hlsDir: string; // absolute output dir for this channel's HLS
  mediaDir: string; // channel media dir the engine ensures exists; track selection is control-plane-owned (D17), so the script no longer reads it directly
  icecastHost: string;
  icecastPort: number;
  icecastSourcePassword: string;
  internalApiUrl: string;
  internalToken: string;
}

export function buildLiquidsoapScript(p: LiquidsoapParams): string {
  // HE-AAC for the low rung only (<=64k) for adaptive mobile (ADR D2); higher
  // rungs stay AAC-LC. HE-AAC needs libfdk_aac (present in the image's ffmpeg
  // build); the native `aac` encoder is LC-only and silently ignores aac_he.
  const hlsStreams = p.hlsBitrates
    .map((b) => {
      const enc =
        b <= 64
          ? `%ffmpeg(format="mpegts", %audio(codec="libfdk_aac", b="${b}k", profile="aac_he"))`
          : `%ffmpeg(format="mpegts", %audio(codec="aac", b="${b}k"))`;
      return `    ("aac_${b}", ${enc})`;
    })
    .join(",\n");

  // Escape double quotes in interpolated strings that could contain them.
  const name = p.name.replace(/"/g, '\\"');

  const emitHls = p.deliveryMode === "hls" || p.deliveryMode === "both";
  const emitIcecast = p.deliveryMode === "icecast" || p.deliveryMode === "both";

  const hlsOutput = emitHls
    ? `
# ── Output: HLS rendition set (CDN-cacheable) ─────────────────────────────────
output.file.hls(
  playlist="live.m3u8",
  segment_duration=4.0,
  segments=6,
  segments_overhead=4,
  temp_dir="${p.hlsDir}",
  "${p.hlsDir}",
  [
${hlsStreams}
  ],
  radio
)
`
    : "";

  const icecastOutput = emitIcecast
    ? `
# ── Output: low-latency Icecast mount (origin-direct, never CDN-fronted) ──────
output.icecast(
  %mp3(bitrate=${p.icecastBitrate}),
  host="${p.icecastHost}",
  port=${p.icecastPort},
  password="${p.icecastSourcePassword}",
  mount="${p.mount}",
  name="${name}",
  radio
)
`
    : "";

  return `# ─────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED by Aerial for channel "${p.slug}". Do not edit by hand.
# Target: Liquidsoap 2.2.x
# ─────────────────────────────────────────────────────────────────────────────
log.level := 3
# Safety net if the container is overridden to run as root (it defaults to the
# non-root 'liquidsoap' user, where this is a no-op). Liquidsoap refuses root otherwise.
settings.init.allow_root := true
settings.harbor.bind_addrs := ["0.0.0.0"]

internal_url = "${p.internalApiUrl}"
internal_token = "${p.internalToken}"

# Post a small JSON body to a control-plane internal hook (fire-and-forget).
def notify(path, payload) =
  ignore(http.post(
    "#{internal_url}#{path}",
    headers=[("Content-Type", "application/json"), ("x-internal-token", internal_token)],
    data=json.stringify(payload)
  ))
end

# Most-recent successfully-authenticated client address. Verified against
# Liquidsoap 2.2.5: the harbor auth callback receives {address,user,password}
# (address = client network address), but on_connect receives only the header
# list — no address. So we capture the address in auth and replay it to the
# status hook for the per-stream session log (ADR D10 source IP).
last_address = ref("")

# Harbor source auth → delegates to the control plane (bcrypt compare, D10;
# schedule-aware in D18). Liquidsoap 2.2.5 passes a record {address,user,password}.
def auth(req) =
  last_address := req.address
  resp = http.post(
    "#{internal_url}/internal/auth",
    headers=[("Content-Type", "application/json"), ("x-internal-token", internal_token)],
    data=json.stringify({mount = "${p.mount}", user = req.user, password = req.password, address = req.address})
  )
  resp.status_code == 200
end

# Live streamer input. on_connect/on_disconnect report "live" status to the control plane.
live = input.harbor(
  "${p.mount}",
  port=${p.harborPort},
  auth=auth,
  buffer=5.0,
  max=15.0,
  on_connect=fun(_) -> notify("/internal/status", {slug = "${p.slug}", live = true, address = last_address()}),
  on_disconnect=fun() -> notify("/internal/status", {slug = "${p.slug}", live = false})
)

# Auto-DJ: the control plane owns track selection (ADR D17). Each time the queue
# needs a track it asks POST /internal/next-track (same internal URL + token
# header as the other hooks). A 200 with a non-empty body is an annotate: URI to
# play; anything else means "nothing playable" → null → the fallback below drops
# to silence via mksafe. Replaces the old watched media directory source.
def next_track() =
  resp = http.post(
    "#{internal_url}/internal/next-track",
    headers=[("Content-Type", "application/json"), ("x-internal-token", internal_token)],
    data=json.stringify({slug = "${p.slug}"})
  )
  if resp.status_code == 200 and string.length(resp) > 0 then
    request.create(resp)
  else
    null()
  end
end
autodj = request.dynamic(id="autodj", next_track)

# Gapless, cue-aware transitions (ADR D12), validated against Liquidsoap 2.2.5:
#   - cue_in/cue_out are honored at request resolution (request.create defaults
#     cue_in_metadata="liq_cue_in", cue_out_metadata="liq_cue_out"); the
#     standalone cue-cutting operator is deprecated in 2.2.5, so it is not used.
#   - crossfade(smart=true) does level-aware, gapless track-to-track fades and
#     honors the per-track liq_cross_duration override; the old dedicated
#     smart-crossfade plugin is absent in 2.2.5, so smart=true replaces it.
# Applied to the Auto-DJ source only: the live harbor keeps its instant,
# track_sensitive=false cutover below (no crossfade latency on go-live).
autodj = crossfade(smart=true, autodj)

# Instant cutover to live the moment a streamer connects (track_sensitive=false);
# Auto-DJ is the floor.
radio = fallback(track_sensitive=false, [live, autodj])
# mksafe guarantees the mount never drops (silence if the queue is empty too).
radio = mksafe(radio)

# Loudness: EBU R128 / LUFS normalization, ON by default (ADR D12). Applied to
# the shared source before the output split, so HLS *and* Icecast are normalized.
# Target -16 LUFS (streaming practice, competitive perceived level) rather than
# broadcast -23 LUFS; lufs=true measures/targets in LUFS (R128 units), not RMS.
# (ffmpeg.filter.loudnorm is the truest integrated-R128 operator and is present
# in the image, but its filter-graph clock cannot be unified with this live
# fallback + dual-output pipeline — so the native LUFS normalizer is used.)
radio = normalize(radio, lufs=true, target=-16.0)

# Now-playing side-channel (D8): push metadata to the control plane.
radio.on_metadata(fun(m) ->
  notify("/internal/metadata", {
    slug = "${p.slug}",
    title = m["title"],
    artist = m["artist"]
  })
)
${hlsOutput}${icecastOutput}`;
}
